name: Auto Close Reopened Issues

on:
  issues:
    types: [reopened]

jobs:
  close_issue:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Close reopened issue
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh issue close ${{ github.event.issue.number }}
