name: Auto Close Reopened Issues

on:
  issues:
    types: [reopened]

jobs:
  close_issue:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Comment on reopened issue
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh issue comment ${{ github.event.issue.number }} --body "@${{ github.event.sender.login }} 님, 추가적인 업무가 있으시면 새로운 이슈를 만들어주시는 건 어떠실까요? :point_right: [**Create a New Issue**](${{ github.server_url }}/${{ github.repository }}/issues/new)<br/>혹시 다시 오픈해야 할 문제가 있으시면 @tooget 님에게 문의를 부탁드려요."
    - name: Close reopened issue
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh issue close ${{ github.event.issue.number }}
