name: "Auto Assign Issue and Pull Request Creator"

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  if_assignee_empty:
    runs-on: ubuntu-latest
    steps:
      - name: "Assign issue creator"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: "github.event_name == 'issues' && github.event.issue.assignees == ''"
        run: |
          gh api repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/assignees \
          --raw-field 'assignees=["${{ github.event.issue.user.login }}"]'
      - name: "Assign pull request creator"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: "github.event_name == 'pull_request' && github.event.pull_request.assignees == ''"
        run: |
          gh api repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/assignees \
          --raw-field 'assignees=["${{ github.event.pull_request.user.login }}"]'
